No highlight in context menu, change  --item-hover-bg-color to  --bg-…
adesurirey/typora-notes-dark-theme pull request #9
Opened 2020-08-19 11:18 UTC by EduardoCastanho

…color-dark

When hover the contexts menus items are not highlighted. This happens because the two states have same color for background 
The highlight is useful for example when one call context menu using the keyboard  for do spell checking replacements

2020-08-20 08:19 UTC, adesurirey commented
Hi @EduardoCastanho and thanks for your contribution. 

Could you explain more what issue you're trying to solve? I don't get it. Maybe add some screenshots?

Merging your commit would break the hover style in outline panel and dropdown because the hovered item would have the same color as the background. This is how it looks currently: 

![image](https://user-images.githubusercontent.com/22000544/90737558-6e4e7f80-e2ce-11ea-9255-54c47f3b5924.png)

2020-08-25 12:45 UTC, adesurirey requested changes
See my previous comment

2020-08-26 13:52 UTC, EduardoCastanho commented
Hi @adesurirey 


Currently the dropdown and  item-hover background color  are the same:

`  --bg-color: #292929;`

![Screenshot from 2020-08-26 12-37-50](https://user-images.githubusercontent.com/11145763/91305735-60ec3600-e7a3-11ea-8c87-27e9da4725ab.png)

And no highlight for the selected/hovered item is displayed  

I think this is not OS/ Windows Manager dependent or even Typora version dependent

With my PR the result is this :
   
![context_with_pr_change](https://user-images.githubusercontent.com/11145763/91307052-5d59ae80-e7a5-11ea-8c25-522f3f0f3162.png)

-------
**But has you correctly notice, my PR will break the outline side bar ... :disappointed:** 

The outline and dropdown bg colors are not the same, but they share the same style for the hover item 

![dropoverout](https://user-images.githubusercontent.com/11145763/91306697-d0165a00-e7a4-11ea-8431-6a8c34dcd559.png)

Maybe creating a specific rule for the item in the dropdown  can solve the issue. 
```css
.context-menu.dropdown-menu li.active a{
  background-color: var(--dark-trait);
}
```

2020-08-26 13:52 UTC, closed without merging

2020-08-26 15:34 UTC, adesurirey commented
Thank you @EduardoCastanho for clarifying this!

Are you on Linux? I don't have that dropdown on macOS. 

I think the best option would be to set the background of the dropdown to `--dark-trait`, same as the sidebar and the outline dropdown. So the light hover background would be visible and we'll have a unified UI over all dropdowns and menus. 

I already did this change recently for the outline popover that used to have the same issue: 
https://github.com/adesurirey/typora-notes-dark-theme/commit/df35a5b2623caefbcf300273e03ea72d95f4b31a#diff-11f34edccf1d6c5cfb341c4e42b4be3aR452-R454

Based on you commit and as I don't see any CSS variables for the context menu, I guess the needed change would be something like this: 
```
.context-menu {
  background-color: var(--dark-trait);
}
```

What do you think of it? Would you like to reopen the PR?

2020-08-26 17:22 UTC, EduardoCastanho commented
Hi 
yes I'm in Linux (Fedora 30)  

> I think the best option would be to set the background of the dropdown to --dark-trait, same as the sidebar and the outline dropdown. So the light hover background would be visible and we'll have a unified UI over all dropdowns and menus.

Do you mean `--bg-color-dark` right? the --dark-trait is darker
I also agree is better to have the same background color for similar components :+1: 

With `--bg-color-dark`
![cenas](https://user-images.githubusercontent.com/11145763/91333814-01ebe880-e7c6-11ea-83e7-c8e17fa20cf0.png)

 For some reason i mess up the my fork and end up by deleting it I cannot reopen this PR
 
I also notice that the margin on the dropdown is short:  
      
![cenas2](https://user-images.githubusercontent.com/11145763/91335008-b5091180-e7c7-11ea-83aa-28e57ae485c1.png)

I suspect this is related with the font, only the monospace themes have this issue

I will check this issues  and compose a new PR in the next days

2020-08-26 18:10 UTC, adesurirey commented
> Do you mean --bg-color-dark right? the --dark-trait is darker

You're right.

Thank you for the screenshots, I like the result!

> I also notice that the margin on the dropdown is short

Yes, or the buttons takes too much space? I don't know.

> only the monospace themes have this issue

I use system fonts in order to have a native look (https://github.com/adesurirey/typora-notes-dark-theme/blob/master/theme/notes-dark.css#L42), is it monospace on Linux? 

Anyway I read a little about this and I think we should change that to: 
```css
--font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Ubuntu, "Helvetica Neue", sans-serif;
```
(see https://fontsarena.com/blog/operating-systems-default-sans-serif-fonts/#:~:text=font%2Dfamily%3A%20system%2Dui,%2C%20Cantarell%2C%20sans%2Dserif%3B&text=Roboto%2C%20Ubuntu%2C%20sans%2Dserif,be%20ok%20for%20Linux%20distros.) 

That may fix the margin issue if it's related to monospace. 

Feel free to open a new PR for all of this 🙂

2020-08-27 06:17 UTC, adesurirey commented
Let's continue the conversation in here: https://github.com/adesurirey/typora-notes-dark-theme/issues/11